//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class DefaultSettings : Neo.ApplicationFramework.Tools.Recipe.Recipe, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_targetPressure700;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_stall_threshold;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_min_allowed_pressure;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_delata_psi_time;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_fill_timeout;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_second_check;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_carr_moving_avg_size;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_disp_moving_avg_size;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_targetPressure350;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_psi_tol;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_h2_toll;
		
		public DefaultSettings()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem targetPressure700
		{
			get
			{
				return this.m_targetPressure700;
			}
			set
			{
				this.m_targetPressure700 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem stall_threshold
		{
			get
			{
				return this.m_stall_threshold;
			}
			set
			{
				this.m_stall_threshold = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem min_allowed_pressure
		{
			get
			{
				return this.m_min_allowed_pressure;
			}
			set
			{
				this.m_min_allowed_pressure = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem delata_psi_time
		{
			get
			{
				return this.m_delata_psi_time;
			}
			set
			{
				this.m_delata_psi_time = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem fill_timeout
		{
			get
			{
				return this.m_fill_timeout;
			}
			set
			{
				this.m_fill_timeout = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem second_check
		{
			get
			{
				return this.m_second_check;
			}
			set
			{
				this.m_second_check = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem carr_moving_avg_size
		{
			get
			{
				return this.m_carr_moving_avg_size;
			}
			set
			{
				this.m_carr_moving_avg_size = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem disp_moving_avg_size
		{
			get
			{
				return this.m_disp_moving_avg_size;
			}
			set
			{
				this.m_disp_moving_avg_size = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem targetPressure350
		{
			get
			{
				return this.m_targetPressure350;
			}
			set
			{
				this.m_targetPressure350 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem psi_tol
		{
			get
			{
				return this.m_psi_tol;
			}
			set
			{
				this.m_psi_tol = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem h2_toll
		{
			get
			{
				return this.m_h2_toll;
			}
			set
			{
				this.m_h2_toll = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.targetPressure700 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.stall_threshold = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.min_allowed_pressure = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.delata_psi_time = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.fill_timeout = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.second_check = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.carr_moving_avg_size = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.disp_moving_avg_size = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.targetPressure350 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.psi_tol = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.h2_toll = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataVersion = ((long)(6));
			this.FieldNames.Add("Default");
			this.Guid = new System.Guid("125ab741-1fec-4576-987b-a9d11482c7c1");
			this.targetPressure700.ColumnName = "targetPressure700";
			this.targetPressure700.DataConnection = "Tags.TargetPressure700";
			this.targetPressure700.Name = "targetPressure700";
			this.targetPressure700.VisualSortOrder = 2;
			this.stall_threshold.ColumnName = "stall_threshold";
			this.stall_threshold.DataConnection = "Tags.STALL_THRESHOLD";
			this.stall_threshold.Name = "stall_threshold";
			this.stall_threshold.VisualSortOrder = 3;
			this.min_allowed_pressure.ColumnName = "min_allowed_pressure";
			this.min_allowed_pressure.DataConnection = "Tags.MIN_ALLOWED_PRESSURE";
			this.min_allowed_pressure.Name = "min_allowed_pressure";
			this.min_allowed_pressure.VisualSortOrder = 4;
			this.delata_psi_time.ColumnName = "delata_psi_time";
			this.delata_psi_time.DataConnection = "Tags.DELTA_PSI_TIME";
			this.delata_psi_time.Name = "delata_psi_time";
			this.delata_psi_time.VisualSortOrder = 5;
			this.fill_timeout.ColumnName = "fill_timeout";
			this.fill_timeout.DataConnection = "Tags.FILL_TIMEOUT";
			this.fill_timeout.Name = "fill_timeout";
			this.fill_timeout.VisualSortOrder = 7;
			this.second_check.ColumnName = "second_check";
			this.second_check.DataConnection = "Tags.SECOND_CHECK";
			this.second_check.Name = "second_check";
			this.second_check.VisualSortOrder = 8;
			this.carr_moving_avg_size.ColumnName = "carr_moving_avg_size";
			this.carr_moving_avg_size.DataConnection = "Tags.CARR_MOVING_AVG";
			this.carr_moving_avg_size.Name = "carr_moving_avg_size";
			this.carr_moving_avg_size.VisualSortOrder = 9;
			this.disp_moving_avg_size.ColumnName = "disp_moving_avg_size";
			this.disp_moving_avg_size.DataConnection = "Tags.DISP_MOVING_AVG";
			this.disp_moving_avg_size.Name = "disp_moving_avg_size";
			this.disp_moving_avg_size.VisualSortOrder = 10;
			this.targetPressure350.ColumnName = "targetPressure350";
			this.targetPressure350.DataConnection = "Tags.TargetPressure350";
			this.targetPressure350.Name = "targetPressure350";
			this.targetPressure350.VisualSortOrder = 11;
			this.psi_tol.ColumnName = "psi_tol";
			this.psi_tol.DataConnection = "Tags.PSI_LOSS_TOL";
			this.psi_tol.Name = "psi_tol";
			this.psi_tol.VisualSortOrder = 12;
			this.h2_toll.ColumnName = "h2_toll";
			this.h2_toll.DataConnection = "Tags.H2SNIFFER_TOL";
			this.h2_toll.Name = "h2_toll";
			this.h2_toll.VisualSortOrder = 13;
			this.RecipeItems.Add(this.targetPressure700);
			this.RecipeItems.Add(this.stall_threshold);
			this.RecipeItems.Add(this.min_allowed_pressure);
			this.RecipeItems.Add(this.delata_psi_time);
			this.RecipeItems.Add(this.fill_timeout);
			this.RecipeItems.Add(this.second_check);
			this.RecipeItems.Add(this.carr_moving_avg_size);
			this.RecipeItems.Add(this.disp_moving_avg_size);
			this.RecipeItems.Add(this.targetPressure350);
			this.RecipeItems.Add(this.psi_tol);
			this.RecipeItems.Add(this.h2_toll);
			this.SchemaVersion = ((long)(55));
			this.TableName = "DefaultSettings";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(DefaultSettings));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
