//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag TargetPressure;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag CurrentPressure;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag InitialPressure;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag FinalPressure;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag GSR;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag LSR;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag STATE;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag pump;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag OutOfOrder;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagLatestLoadedRecipeName;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MOVING_AVG_SIZE;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag STALL_THRESHOLD;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag MIN_ALLOWED_PRESSURE;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag DELTA_PSI_TIME;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag STALL_CONFIRMATION_CNT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag STALL_TIMEOUT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag FILL_TIMEOUT;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag SECOND_CHECK;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagCommunicationErrors;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag modID;
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagCurrentScreenId;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.TargetPressure = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("TargetPressure", "Controller1.DataItem1", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.CurrentPressure = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("CurrentPressure", "Controller1.DataItem5", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.InitialPressure = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("InitialPressure", "Controller1.DataItem6", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.FinalPressure = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("FinalPressure", "Controller1.DataItem7", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.GSR = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("GSR", "Controller1.DataItem4", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.LSR = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("LSR", "Controller1.DataItem3", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.STATE = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("STATE", "Controller1.DataItem2", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.pump = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("pump", "Controller1.DataItem8", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.OutOfOrder = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("OutOfOrder", "Controller1.DataItem10", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.SystemTagLatestLoadedRecipeName = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Latest Loaded Recipe Name", "SystemTagLatestLoadedRecipeName", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), ((short)(100)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, true, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Name of the latest loaded recipe", ((short)(1)), "", "");
			this.MOVING_AVG_SIZE = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MOVING_AVG_SIZE", "Controller1.DataItem9", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.STALL_THRESHOLD = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("STALL_THRESHOLD", "Controller1.DataItem11", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.MIN_ALLOWED_PRESSURE = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("MIN_ALLOWED_PRESSURE", "Controller1.DataItem12", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.DELTA_PSI_TIME = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("DELTA_PSI_TIME", "Controller1.DataItem13", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.STALL_CONFIRMATION_CNT = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("STALL_CONFIRMATION_CNT", "Controller1.DataItem14", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.STALL_TIMEOUT = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("STALL_TIMEOUT", "Controller1.DataItem15", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.FILL_TIMEOUT = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("FILL_TIMEOUT", "Controller1.DataItem16", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.SECOND_CHECK = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("SECOND_CHECK", "Controller1.DataItem17", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.SystemTagCommunicationErrors = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Communication Errors", "SystemTagCommunicationErrors", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Number of active communication errors on all controllers", ((short)(1)), "", "");
			this.modID = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("modID", "Controller1.DataItem18", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "", null);
			this.SystemTagCurrentScreenId = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Current Screen Id", "SystemTagCurrentScreenId", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "The ID of the current screen", ((short)(1)), "", "");
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.SystemTagLatestLoadedRecipeName.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.SystemTagCommunicationErrors.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue("0"), 0, new string[0], new string[0], true));
			this.SystemTagCurrentScreenId.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(new Neo.ApplicationFramework.Interfaces.VariantValue(-1), 0, new string[0], new string[0], true));
			this.LightweightTags.Add(this.TargetPressure);
			this.LightweightTags.Add(this.CurrentPressure);
			this.LightweightTags.Add(this.InitialPressure);
			this.LightweightTags.Add(this.FinalPressure);
			this.LightweightTags.Add(this.GSR);
			this.LightweightTags.Add(this.LSR);
			this.LightweightTags.Add(this.STATE);
			this.LightweightTags.Add(this.pump);
			this.LightweightTags.Add(this.OutOfOrder);
			this.GlobalDataItems.Add(this.SystemTagLatestLoadedRecipeName);
			this.LightweightTags.Add(this.MOVING_AVG_SIZE);
			this.LightweightTags.Add(this.STALL_THRESHOLD);
			this.LightweightTags.Add(this.MIN_ALLOWED_PRESSURE);
			this.LightweightTags.Add(this.DELTA_PSI_TIME);
			this.LightweightTags.Add(this.STALL_CONFIRMATION_CNT);
			this.LightweightTags.Add(this.STALL_TIMEOUT);
			this.LightweightTags.Add(this.FILL_TIMEOUT);
			this.LightweightTags.Add(this.SECOND_CHECK);
			this.GlobalDataItems.Add(this.SystemTagCommunicationErrors);
			this.LightweightTags.Add(this.modID);
			this.GlobalDataItems.Add(this.SystemTagCurrentScreenId);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
